version: '3'

services:
  web:
    build: .
    command: gunicorn smells_like_devs_cooking_api.wsgi:application --bind 0.0.0.0:8000 --workers 10
    volumes:
      - .:/code
    ports:
      - 8000:8000
